/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Slayer
 */
public class Frm_MenuPrin extends javax.swing.JFrame {

    /**
     * Creates new form Frm_MenuPrin
     */
    public Frm_MenuPrin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_menuProductos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbtn_salir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jtxt_agregarProductos = new javax.swing.JMenuItem();
        jtxt_actualizarProductos = new javax.swing.JMenuItem();
        jtxt_listarProductos = new javax.swing.JMenuItem();
        jtxt_eliminarProductos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setBackground(new java.awt.Color(255, 102, 102));

        jbtn_menuProductos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtn_menuProductos.setText("Productos");
        jbtn_menuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_menuProductosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("MENU PRINCIPAL");

        jbtn_salir.setText("Salir");
        jbtn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_salirActionPerformed(evt);
            }
        });

        jMenu1.setText("Productos");

        jtxt_agregarProductos.setText("Agregar Productos");
        jtxt_agregarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_agregarProductosActionPerformed(evt);
            }
        });
        jMenu1.add(jtxt_agregarProductos);

        jtxt_actualizarProductos.setText("Actualizar Productos");
        jtxt_actualizarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_actualizarProductosActionPerformed(evt);
            }
        });
        jMenu1.add(jtxt_actualizarProductos);

        jtxt_listarProductos.setText("Listar Productos");
        jMenu1.add(jtxt_listarProductos);

        jtxt_eliminarProductos.setText("Eliminar Productos");
        jMenu1.add(jtxt_eliminarProductos);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtn_salir)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jbtn_menuProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jbtn_menuProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jbtn_salir)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_salirActionPerformed
    System.exit(0);
    }//GEN-LAST:event_jbtn_salirActionPerformed

    private void jtxt_agregarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_agregarProductosActionPerformed
    Frm_AgregarProducto agregar = new Frm_AgregarProducto();
    agregar.setVisible(true);
    }//GEN-LAST:event_jtxt_agregarProductosActionPerformed

    private void jtxt_actualizarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_actualizarProductosActionPerformed
    Frm_ActProducto actualizar = new Frm_ActProducto();
    actualizar.setVisible(true);
    }//GEN-LAST:event_jtxt_actualizarProductosActionPerformed

    private void jbtn_menuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_menuProductosActionPerformed
    Frm_MenuProductos productos = new Frm_MenuProductos();
    productos.setVisible(true);
    dispose();
    }//GEN-LAST:event_jbtn_menuProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_MenuPrin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_MenuPrin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_MenuPrin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_MenuPrin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_MenuPrin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jbtn_menuProductos;
    private javax.swing.JButton jbtn_salir;
    private javax.swing.JMenuItem jtxt_actualizarProductos;
    private javax.swing.JMenuItem jtxt_agregarProductos;
    private javax.swing.JMenuItem jtxt_eliminarProductos;
    private javax.swing.JMenuItem jtxt_listarProductos;
    // End of variables declaration//GEN-END:variables
}
